USE [master]
GO
/****** Object:  Database [FacturacionDB]    Script Date: 16/11/2022 22:07:54 ******/
CREATE DATABASE [FacturacionDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FacturacionDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FacturacionDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FacturacionDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FacturacionDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FacturacionDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FacturacionDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FacturacionDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FacturacionDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FacturacionDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FacturacionDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FacturacionDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FacturacionDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FacturacionDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FacturacionDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FacturacionDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FacturacionDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FacturacionDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FacturacionDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FacturacionDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FacturacionDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FacturacionDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FacturacionDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FacturacionDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FacturacionDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FacturacionDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FacturacionDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FacturacionDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FacturacionDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FacturacionDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FacturacionDB] SET  MULTI_USER 
GO
ALTER DATABASE [FacturacionDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FacturacionDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FacturacionDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FacturacionDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FacturacionDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FacturacionDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FacturacionDB', N'ON'
GO
ALTER DATABASE [FacturacionDB] SET QUERY_STORE = OFF
GO
USE [FacturacionDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NombreCategoria] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[Apellido] [nvarchar](150) NOT NULL,
	[Direccion] [nvarchar](350) NULL,
	[Telefono] [nvarchar](50) NULL,
	[Email] [nvarchar](350) NULL,
	[FechaNacimiento] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Factura]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Factura](
	[NumeroFactura] [int] IDENTITY(1,1) NOT NULL,
	[FechaExpedicion] [datetime2](7) NOT NULL,
	[ClienteId] [int] NOT NULL,
 CONSTRAINT [PK_Factura] PRIMARY KEY CLUSTERED 
(
	[NumeroFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ItemVenta]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ItemVenta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumeroFactura] [int] NOT NULL,
	[ProductoId] [int] NOT NULL,
	[PrecioUnitario] [decimal](18, 2) NOT NULL,
	[CantidadVendida] [int] NOT NULL,
 CONSTRAINT [PK_ItemVenta] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 16/11/2022 22:07:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[PrecioUnitario] [decimal](18, 2) NOT NULL,
	[CantidadExistencia] [int] NOT NULL,
	[CategoriaId] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Factura_ClienteId]    Script Date: 16/11/2022 22:07:55 ******/
CREATE NONCLUSTERED INDEX [IX_Factura_ClienteId] ON [dbo].[Factura]
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ItemVenta_NumeroFactura]    Script Date: 16/11/2022 22:07:55 ******/
CREATE NONCLUSTERED INDEX [IX_ItemVenta_NumeroFactura] ON [dbo].[ItemVenta]
(
	[NumeroFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ItemVenta_ProductoId]    Script Date: 16/11/2022 22:07:55 ******/
CREATE NONCLUSTERED INDEX [IX_ItemVenta_ProductoId] ON [dbo].[ItemVenta]
(
	[ProductoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Producto_CategoriaId]    Script Date: 16/11/2022 22:07:55 ******/
CREATE NONCLUSTERED INDEX [IX_Producto_CategoriaId] ON [dbo].[Producto]
(
	[CategoriaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Factura]  WITH CHECK ADD  CONSTRAINT [FK_Factura_Cliente_ClienteId] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Factura] CHECK CONSTRAINT [FK_Factura_Cliente_ClienteId]
GO
ALTER TABLE [dbo].[ItemVenta]  WITH CHECK ADD  CONSTRAINT [FK_ItemVenta_Factura_NumeroFactura] FOREIGN KEY([NumeroFactura])
REFERENCES [dbo].[Factura] ([NumeroFactura])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ItemVenta] CHECK CONSTRAINT [FK_ItemVenta_Factura_NumeroFactura]
GO
ALTER TABLE [dbo].[ItemVenta]  WITH CHECK ADD  CONSTRAINT [FK_ItemVenta_Producto_ProductoId] FOREIGN KEY([ProductoId])
REFERENCES [dbo].[Producto] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ItemVenta] CHECK CONSTRAINT [FK_ItemVenta_Producto_ProductoId]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Categoria_CategoriaId] FOREIGN KEY([CategoriaId])
REFERENCES [dbo].[Categoria] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Categoria_CategoriaId]
GO
USE [master]
GO
ALTER DATABASE [FacturacionDB] SET  READ_WRITE 
GO
